name = "blog"
compatibility_date = "2026-04-30"

[assets]
directory = "./out"
not_found_handling = "404-page"

[vars]
S3_PUBLIC_ENDPOINT = "https://s3.seokgukim.com"
S3_BLOG_PATH = "/blog"
S3_POST_DISCOVERY = "manifest"
